Repository cryptoeconomicslab/plasma-chamber, pull requests merged in 2018-10, with the labels that each got.

#44 Update RootChain.test.js
  rootchain/test/RootChain.test.js
Labels: bug

#47 Update Overview
  README.md
Labels: enhancement

#62 Add SparseMerkleTree in child chain
  childchain/lib/block.js
  childchain/lib/smt.js
  childchain/lib/tx.js
  childchain/test/block_test.js
  childchain/test/smt_test.js
Labels: ChildChain, enhancement

#61 Fix short address decoding bug
  rootchain/contracts/RLP.sol
Labels: bug
